/**
 * Default playlist pool + **prebaked** landing backgrounds.
 *
 * The homepage needs drifting album covers to be visible the moment
 * the page paints. Hitting Spotify every load is:
 *
 *   - unreliable (429 rate limits, region 404s, slow hydration of
 *     hundreds of tracks for an editorial list),
 *   - slow (first paint gets blocked behind the entire hydrate
 *     pipeline),
 *   - and noisy (the user's browser sees progress bars / errors
 *     that are really about our ambient scene).
 *
 * Instead we ship a static snapshot (`src/data/landingBackgrounds.json`)
 * generated by `scripts/prebake-landing.ts`. The snapshot is capped to
 * the first 60 tracks per playlist — plenty of covers to keep the
 * visualizer lively, small enough (~170 KB) to inline into the JS
 * bundle. Re-run `npm run prebake:landing` whenever the pool below
 * changes.
 *
 * Pool configuration:
 *
 *   - `DEFAULT_PLAYLIST_POOL` below is the canonical list, edited by
 *     hand. These are the URLs/IDs the prebake script reads.
 *   - `NEXT_PUBLIC_SPOTIFY_DEFAULT_PLAYLIST_IDS` (comma/space
 *     separated) overrides which prebaked playlists are eligible for
 *     random selection at runtime. Only `NEXT_PUBLIC_*` is honored
 *     because this module is imported into client components.
 *     Playlists listed in the env but missing from the snapshot are
 *     ignored with a warning.
 */

import landingBackgrounds from "@/data/landingBackgrounds.json";
import type { Playlist } from "./types";
import { extractPlaylistId } from "./extractPlaylistId";

/**
 * Edit this list and re-run `npm run prebake:landing`. Entries may be
 * raw IDs, `spotify:playlist:…` URIs, or `https://open.spotify.com/…`
 * URLs — anything `extractPlaylistId()` can parse.
 */
export const DEFAULT_PLAYLIST_POOL: readonly string[] = [
  "https://open.spotify.com/playlist/12rEkz0g1nd0FXSDH5BXf1?si=fdda7e6f2dfc4f6e",
  "https://open.spotify.com/playlist/6ut7pit5G4Zs8NCjtJK7HQ?si=9f5e5aef0fd74bdb",
  "https://open.spotify.com/playlist/7pOh62kXHilo9qF3oRp3OW?si=fcce812b56cf4e02",
  "https://open.spotify.com/playlist/5qtILX0Ak7EBPYCaXDooKh?si=fa472b1e8ca94950",
  "https://open.spotify.com/playlist/3q5KL3QLFMvCjhUNMi5Q3g?si=e02c4f4de013471c",
  "https://open.spotify.com/playlist/2eThEejmgDsA4ncveXUATo?si=657b7b2ef3f94636",
  "https://open.spotify.com/playlist/1UH5r9N65GxnyLYUufe39C?si=04f9635475a24482",
  "https://open.spotify.com/playlist/3E2r9WGe4Npg9tQyBS8HQM?si=22dec44007fc498a",
  "https://open.spotify.com/playlist/7vpmwrn2kgoawqFHhgOuZF?si=2cb30cb0b92745b2",
  "https://open.spotify.com/playlist/7LtaSOZCGWNpJ4Iwgw4Sl2?si=20ab6a2efac14eb4",
];

/**
 * Shape of the prebaked JSON file. Kept loose here so a future change
 * to the snapshot format (adding a `generatedAt` sibling field, etc.)
 * doesn't force a type update. Unknown fields are just ignored.
 */
interface LandingBackgroundsFile {
  generatedAt: string;
  maxTracksPerPlaylist: number;
  playlists: Playlist[];
}

const SNAPSHOT = landingBackgrounds as LandingBackgroundsFile;

/**
 * Every prebaked playlist, in the order they were baked. Safe to
 * import from client components — the file is a plain JSON blob.
 */
export const PREBAKED_LANDING_PLAYLISTS: readonly Playlist[] =
  SNAPSHOT.playlists ?? [];

/**
 * Apply the optional `NEXT_PUBLIC_SPOTIFY_DEFAULT_PLAYLIST_IDS`
 * override. Entries that aren't present in the prebaked snapshot are
 * dropped (with a warning in dev) because we intentionally only ship
 * art for the hand-curated pool.
 */
function resolveEligiblePlaylists(): readonly Playlist[] {
  const override = process.env.NEXT_PUBLIC_SPOTIFY_DEFAULT_PLAYLIST_IDS;
  if (typeof override !== "string" || override.trim() === "") {
    return PREBAKED_LANDING_PLAYLISTS;
  }

  const wanted = override
    .split(/[,\s]+/)
    .map((s) => s.trim())
    .map((s) => extractPlaylistId(s) ?? s)
    .filter(Boolean);

  if (wanted.length === 0) return PREBAKED_LANDING_PLAYLISTS;

  const byId = new Map(
    PREBAKED_LANDING_PLAYLISTS.map((p) => [p.id, p] as const)
  );
  const picked: Playlist[] = [];
  for (const id of wanted) {
    const hit = byId.get(id);
    if (hit) picked.push(hit);
    else if (process.env.NODE_ENV !== "production") {
      console.warn(
        `[defaultPlaylists] NEXT_PUBLIC_SPOTIFY_DEFAULT_PLAYLIST_IDS references "${id}" ` +
          `but it isn't in the prebaked snapshot — re-run \`npm run prebake:landing\` after editing DEFAULT_PLAYLIST_POOL.`
      );
    }
  }
  return picked.length > 0 ? picked : PREBAKED_LANDING_PLAYLISTS;
}

/** Prebaked playlists eligible to be shown as a landing background. */
export function getLandingPlaylistPool(): readonly Playlist[] {
  return resolveEligiblePlaylists();
}

/**
 * Pick one prebaked playlist uniformly at random. Returns `null` if
 * the snapshot is empty (which should never happen in a shipped build
 * — the prebake refuses to write a zero-playlist file).
 */
export function pickRandomLandingPlaylist(): Playlist | null {
  const pool = getLandingPlaylistPool();
  if (pool.length === 0) return null;
  const i = Math.floor(Math.random() * pool.length);
  return pool[i];
}

/**
 * @deprecated Kept so any lingering callers still compile, but the
 * homepage should consume `pickRandomLandingPlaylist()` directly —
 * there's no network fetch involved anymore.
 */
export function pickRandomDefaultPlaylist(): string {
  const picked = pickRandomLandingPlaylist();
  if (picked) return picked.id;
  return DEFAULT_PLAYLIST_POOL[0] ?? "";
}
